markdown: kramdown
highlighter: rouge
title: Hydeout
tagline: A Jekyll theme
description: >-
  The <a href="http://hyde.getpoole.com" target="_blank">Hyde</a> theme for <a
  href="http://jekyllrb.com" target="_blank">Jekyll</a>, refreshed.
url: ''
baseurl: ''
author:
  name: Andrew Fong
  url: 'https://twitter.com/fongandrewc'
paginate: 5
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
sidebar_home_link: true
